import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'app.dart';
import 'firebase_options.dart';
import 'providers/alarm_provider.dart';
import 'providers/auth_provider.dart';
import 'providers/focus_provider.dart';
import 'providers/navigation_provider.dart';
import 'providers/settings_provider.dart';
import 'providers/task_provider.dart';
import 'services/alarm_storage_service.dart';
import 'services/auth_service.dart';
import 'services/focus_session_storage_service.dart';
import 'services/firestore_service.dart';
import 'services/settings_storage_service.dart';
import 'services/storage_service.dart';
import 'services/task_storage_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (kEnableAuthFlow) {
    // Replace lib/firebase_options.dart with the file generated by FlutterFire
    // CLI before connecting FocusMate to a real Firebase project.
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  }

  runApp(
    MultiProvider(
      providers: [
        Provider<StorageService>(create: (_) => StorageService()),
        Provider<AlarmStorageService>(create: (_) => AlarmStorageService()),
        Provider<SettingsStorageService>(
          create: (_) => SettingsStorageService(),
        ),
        Provider<TaskStorageService>(create: (_) => TaskStorageService()),
        Provider<FocusSessionStorageService>(
          create: (_) => FocusSessionStorageService(),
        ),
        ChangeNotifierProvider<AlarmProvider>(
          create: (context) => AlarmProvider(
            context.read<AlarmStorageService>(),
          ),
        ),
        ChangeNotifierProvider<TaskProvider>(
          create: (context) => TaskProvider(
            context.read<TaskStorageService>(),
          ),
        ),
        ChangeNotifierProvider<SettingsProvider>(
          create: (context) => SettingsProvider(
            context.read<SettingsStorageService>(),
          ),
        ),
        ChangeNotifierProvider<FocusProvider>(
          create: (context) => FocusProvider(
            storageService: context.read<FocusSessionStorageService>(),
            taskProvider: context.read<TaskProvider>(),
            settingsProvider: context.read<SettingsProvider>(),
          ),
        ),
        if (kEnableAuthFlow) ...[
          Provider<FirestoreService>(create: (_) => FirestoreService()),
          Provider<AuthService>(
            create: (context) => AuthService(
              firestoreService: context.read<FirestoreService>(),
            ),
          ),
          ChangeNotifierProvider<AuthProvider>(
            create: (context) => AuthProvider(context.read<AuthService>()),
          ),
        ],
        ChangeNotifierProvider<NavigationProvider>(
          create: (_) => NavigationProvider(),
        ),
      ],
      child: const FocusMateApp(),
    ),
  );
}
